/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Interface_constants.h"

namespace UpdateService {

const InterfaceConstants g_Interface_constants;

InterfaceConstants::InterfaceConstants() {
}

} // namespace

